### ISSUE TITLE
On Mac the input sometimes seems to have a delay or is blocked entirely

### ISSUE THREAD

**Issue by gurkenlabs** [gurkenlabs/litiengine#10]
**Player Feedback From LDJAM**
My biggest problem (which nobody else seems to have reported, so I wonder if it’s Mac-specific) was that I kept getting stuck in walls and couldn’t move for a while. Was especially frustrating on the last level where I’d fought hard for a couple of minutes to get the last person to the spot where I could aim at them and they finally went there but I got stuck on the way there for like 20 seconds and I missed the opportunity.

**Comment by gurkenlabs** [comment]
With commit f62356885e4e65cd6e70431d8ac8b9e380578128 we've fixed a major issue with the gameloop that might be responsible for this. Unfortunately I cannot confirm this due to the lack of a mac machine :(

**Comment by steffen-wilke** [comment]
Noone reported this again until now. Closing this issue for now.
