### ISSUE TITLE
Implement a reusable component for (UI) animations

### ISSUE THREAD

**Issue by gurkenlabs** [gurkenlabs/litiengine#120]
**Problem**
Currently, UI animations have to be implemented individually and there's no unified component, although a solution for it is always very similar.

**Target State**
We need to unify these animations with a general implementation. This could be similar to the [Animator ](https://developer.android.com/reference/android/animation/Animator) from the android SDK. 
Another source of inspiration would be Unity [Animation Curves](https://docs.unity3d.com/Manual/animeditor-AnimationCurves.html) .

The component that will be implemented can potentially be reused to animate all kinds of things that can be represented by the following types:

**Supported Types**
 * `Color`
 * `int`
 * `float`
 * `double`
 * `Point2D` (x and y will be scaled equally)
 * `boolean` (threshold must be specified)
 
**Features**
 * relative value
 * opt. absolut value
 * different interpolation types between values
   * Linear
   * In-Out
   * sigmoid?
   * sinus
   * custom functions
 * repetition count (1-loop)
 * Custom Callback
   * Color
   * float 0.0-1.0
   * ...
 * Extend `GuiComponent` to support hover/focus animations

**Comment by nightm4re94** [comment]
This has become redundant due to #204.
