### ISSUE TITLE
Wavy rendering when clamping to map

### ISSUE THREAD

**Issue by TheRamenChef** [gurkenlabs/litiengine#123]
I noticed a little fix you had in the `Camera` class: `focus.getY() + 0.01`. Unfortunately, when the camera is clamped to the map, it skips over the fix.

**Comment by gurkenlabs** [comment]
I wouldn't call this a "fix" 😄
Its much more a workaround for something that we don't fully understand and didn't find any information about. Actually, we observed a similar behavior with the Tiled Editor so it doesn't seem to be a Java exclusive issue.

Nevertheless, you are right that this is not being applied when the camera is clamped. So a quick improvement is to also apply this when the camera is clamped.

Long term solution would be to investigate this issue some more and get to the actual issue that causes this wavy rendering.
