### ISSUE TITLE
Updated example code

### ISSUE THREAD

**Issue by bananashavings** [gurkenlabs/litiengine#126]
Hey,

I recently saw [this post](https://github.com/gurkenlabs/litiengine/issues/34) that showed some sample code for a project. I am wondering if you could post a new example with a little bit more code that is up to date. I would sincerely appreciate it if you could do this.  

On a separate note, I am currently developing my own game engine in Java (it is much simpler that Litiengine), and I am wondering what the best way to reach out to you is for some questions I have. I completely understand if you don't have time to answer any questions, but if you do, I would be very thankful.

Thanks!

**Comment by gurkenlabs** [comment]
Thanks for your interest. We'll update the example code to match the current version of the engine.
If you have any questions, feel free to contact us on twitter, facebook or via mail (see our [contact information](https://github.com/gurkenlabs/litiengine#contacts)). Also if the question is somehow related to the LITIengine implementation, you can just open up a issue with the question label.

**Comment by bananashavings** [comment]
Sounds great! Please feel free to let me know when you have the updated example completed. Thanks!

**Comment by nightm4re94** [comment]
We've made the code for our recent LDJAM42 game publicly available.
Check out the [GitHub Repo for "GoIn - Behave or GET LOST"](https://github.com/gurkenlabs/litiengine-ldjam42) to get some insights about game development with LITIengine.
