### ISSUE TITLE
EntityControllerManager() new Version?

### ISSUE THREAD

**Issue by EweLoHD** [gurkenlabs/litiengine#132]
Like mentioned in #126 the Example mentioned here: #34 is outdated. I got the code working, except this little Part: 
```java
Game.getEntityControllerManager().addController(player, new AnimationController(new Animation(playerSprite, true)));
      Game.getEntityControllerManager().addController(player, new KeyboardEntityController<>(player));
```
What is the new Version or Replacemnet for that? 

Thank you in advance 👌

**Comment by EweLoHD** [comment]
Okay, could you please update the whole Example? Because since the 0.4.12 nearly every line of the code is outdated! It shouldn't be so difficult for you to update such a small Example. Without Example or JavaDoc the Libary is useless (for me).

**Comment by gurkenlabs** [comment]
We've just started a blog section on our Website.

The first thing, we're going to write there is a three part tutorial series on how to get started with the LITIengine.

You can check it out [HERE](https://litiengine.com/blog/).

**Comment by EweLoHD** [comment]
Nice! Thanks.

**Comment by nightm4re94** [comment]
Sorry for the late answer! 
We've made the code for our LDJAM42 project publicly available. You might want to look at the [PartyGuest](https://github.com/gurkenlabs/litiengine-ldjam42/blob/master/src/de/gurkenlabs/ldjam42/entities/PartyGuest.java) class, for example:

`79    this.setController(MovementController.class, new PartyGuestController(this));`

that's the new way of adding Controllers to Entities.
For an example on adding an AnimationController, see the [Creature](https://github.com/gurkenlabs/litiengine/blob/master/src/de/gurkenlabs/litiengine/entities/Creature.java) class. 

`45     this.addController(new CreatureAnimationController<Creature>(this, true));`
