### ISSUE TITLE
Set default Appearance and Font on the Graphics2D object

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine#158]
The original thought here was that we have the static `GuiProperties` which are currently used as default for all `GuiComponent` instances. This also includes a default font. For normal text rendering on the `Graphics2D` object, these values are ignored though.

We should evaluate if we should also set these default values (or separate default values) on the `Graphics2D` object at the start of the `RenderLoop`

**Comment by TheRamenChef** [comment]
What would these defaults be?

**Comment by steffen-wilke** [comment]
@TheRamenChef I've updated the description of this issue accordingly.

**Comment by steffen-wilke** [comment]
Specifying a default font for all rendering operations is already possible using `    Game.window().getRenderComponent().setFont(MY-CUSTOM-FONT);`
