### ISSUE TITLE
Take care of jaxb dependencies for Java 9 and newer

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine#162]
> The JAXB APIs are considered to be Java EE APIs, and therefore are no longer contained on the default class path in Java SE 9. In Java 11 they are completely removed from the JDK.

I think we need to reference the maven libraries to properly solve this in a future prove manner.

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by TheRamenChef** [comment]
Considering that LITIEngine is built with Gradle, [this answer](
https://stackoverflow.com/a/51235096/6392939) could be useful.

**Comment by TheRamenChef** [comment]
It's still not working for me.

**Comment by steffen-wilke** [comment]
> It's still not working for me.

Which Java Version are you using? 
Which LITIengine version are you using?
What exactly is not working?

**Comment by PH0lder** [comment]
On Java 11.0.1 on Windows 10 64bit with utiliti-v0.4.15-alpha.exe, when trying to load tilesets or maps I get:
SEVERE    Game crashed! :(
SEVERE    Implementation of JAXB-API has not been found on module path or classpath.

**Comment by steffen-wilke** [comment]
I think we need to find a good strategy here to support Java 9 upwards and still remain compatible to Java 8. Not sure yet how to achieve that but we'll have a look at this soon.

**Comment by steffen-wilke** [comment]
The issue will be fixed with the release of  ` v0.4.16-alpha`.
