### ISSUE TITLE
@ScreenInfo is missing

### ISSUE THREAD

**Issue by makhnnar** [gurkenlabs/litiengine#165]
This page: https://litiengine.com/getting-started-learning-the-basics/, shows how to set an Screen, but when i trie to use @ScreenInfo annotation, there isn't any annotition with that name

**Comment by TheRamenChef** [comment]
That's because `@ScreenInfo` was removed in the latest build. Use a call to the new `Screen` constructor to set the name instead.

**Comment by steffen-wilke** [comment]
I've updated the documentation to reflect this change.
