### ISSUE TITLE
Rendering an image

### ISSUE THREAD

**Issue by Glenn900** [gurkenlabs/litiengine#170]
Hi,

Your project is really interesting and awesome and I was already being able to set up the black screen and play sounds.

Now I want to render a single image, at a certain Position on my Black Screen.

For instance with a code conceptually looking like Game.getRenderEngine().drawImage(Game.getCurrentScreen(), "my_image.jpg", new Position(4,5)); .

Is that possible? How can I achieve that?

Best regards,
Glenn

**Comment by nightm4re94** [comment]
Hi and thank you for your interest. You can, for example, do this in the render method of your screen or any other GuiComponent. Since the last refactoring on the renderengine, the code will look like this : ImageRenderer.render(g,  img, x, y) 
g is your graphics object, img your image, and x and y the rendering coordinates. 
Does this answer your question? 
Best, 
Matthias

**Comment by TheRamenChef** [comment]
You can't do this with the black screen. You need to create a `Screen`:

    import de.gurkenlabs.litiengine.Game;
    import de.gurkenlabs.litiengine.graphics.ImageRenderer;
    import de.gurkenlabs.litiengine.gui.screens.Screen;

    public class MyScreen extends Screen {
        public MyScreen() {
            super("screen_name_here");
        }

        @Override
        public void render(Graphics2D g) {
            ImageRenderer.renderImage(g, image, x, y); // more on this below
        }
    }

In your main method, add the following code to display the screen:

    Game.getScreenManager().displayScreen(new MyScreen());

In your screen's `render` method, `image` should be a variable pointing to the image you want to render, and `x` and `y` are the coordinates. To load your image, you can use a combination of `ImageIO.read` and `ClassLoader.getResourceAsStream`.

**Comment by steffen-wilke** [comment]
To get an image resource you can also just use the `de.gurkenlabs.litiengine.Resources` class.
```java
Resources.getImage("example.png")
```
This will internally load the resource and also provide a caching mechanism if the image was previously already loaded somewhere in your code.
