### ISSUE TITLE
On triggers

### ISSUE THREAD

**Issue by TheRamenChef** [gurkenlabs/litiengine#176]
It's kind of strange how a trigger can activate itself, and inconvenient when I want to set up a one-time collision trigger. It would also help to be able to override the `activate` method more easily to add more functionality.

**Comment by steffen-wilke** [comment]
I don't fully understand the problem/request here. Could you please describe it in more detail?

Have you tried to use the `Trigger.isOneTime` flag combined with `TriggerActivation.COLLISION`?

The logic for activating a `Trigger` is currently implemented in its `update()` method. If you want to further specify who can activate the `Trigger`, you could provide activators which would tell the trigger which entities can activate it. Another option would be to add a `TriggerActivatingCondition` which is essentially just a simple check against a provided `TriggerEvent` that controls whether the `Trigger` can be activated by this event.

> It would also help to be able to override the activate method more easily to add more functionality.

Are we speaking about a custom `Trigger` implementation that behaves somewhat different from the "normal" `Trigger` implementation? What functionality exactly are we talking about here?
