### ISSUE TITLE
Implement "EnvironmentManager"

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine#196]
At the moment, there is no clear way to manage multiple environment instances in the engine. You always have to write something like a `GameManager` that handles the access to multiple environments and e.g. keeps their instances in a list. Also, the `Game` class currently contains methods and callbacks for when an environment was loaded. This should not be part of the `Game` class directly.

Scripting some additional map behavior (e.g. onEnter, onExit, update, ...) also requires additional infrastructure. For every game that we've written with the LITIengine so far, we've always had a slightly different approach to that but the general requirement for such a unit was always there.

We should implement an `EnvironmentManager` (name still up-for-discussion) that provides a basic backbone for managing all environments in the game without limiting the current possiblities. This would:
 * make the engine more accessible to new devs
 * separate the `Environment` logic from the `Game` class
 * make it possible to provide a tested an well tought out infrastructure for a problem that somehow exists in any game with more than one `Map`

**Comment by TheRamenChef** [comment]
Currently, I have an issue in my project where the screen flickers when the environment changes. I know how I could fix it, but it would require an `Entity.getEnvironment` method to resolve entity references when the environment is loading but not yet displayed to the player.
