### ISSUE TITLE
Fix failing unit test "GameTest.testStartup "

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine#197]
Currently, the `GameTest.testStartup` unit test is failing on the CI.
It seems like this issue is somehow related to the unit test's executor. If I do a `gradle clean` followed by a `gradle check` or `gradle test` I can reproduce this locally.
If `gradle check` or `gradle test`  is executed consecutively, the test succeeds...

If I run the Unit Tests from the Eclipe UI it won't ever fail, even after a full cleanup of the project.

**Comment by TheRamenChef** [comment]
I think the problem is that the `initialized` flag isn't reset after unit tests, and if it's already set, the `EnvironmentListener`s aren't called.

I tried to fix it myself by combining the unit tests in that class, but there must be another test that's calling `Game.init`.

**Comment by steffen-wilke** [comment]
Yes, that was also my impression. There are some unit tests that need the game to be initialized since they access some of the infrastructures. But this is currently not reset. I'm not familiar with how Gradle executes unit tests in comparison to other executors but my suggestion would also be that some of the tests are interfering with each other in a Gradle execution environment and the static `Game` instance is getting reused which now causes issues in this particular test.
