### ISSUE TITLE
Environment(String mapPath) constructor is throwing a FileNotFoundException

### ISSUE THREAD

**Issue by Spiff77** [gurkenlabs/litiengine#201]
Hello,

I tried to instantiate an Environment but

    Environment e = new Environment("tiles.tmx");

Didn't work, had to use

    Environment e = new Environment(Resources.maps().get("tiles1.tmx"));

reason:

    SEVERE: tiles (No such file or directory)
    java.io.FileNotFoundException: tiles (No such file or directory)
    	at java.io.FileInputStream.open0(Native Method)

Seems like it didn't take the file extension. 

**Info: I am using the git version as a jar**

**Comment by TheRamenChef** [comment]
Where precisely is `tiles1.tmx` located?

**Comment by Spiff77** [comment]
It's in a resources source folder:
![capture d ecran 2018-12-19 a 17 08 16](https://user-images.githubusercontent.com/600608/50232243-c8d46180-03b0-11e9-8408-1e6792ced65e.png)

**Comment by steffen-wilke** [comment]
Thank's for finding this. This was actually an issue in the latest version.
