### ISSUE TITLE
Asynchronous loading of resources

### ISSUE THREAD

**Issue by TheRamenChef** [gurkenlabs/litiengine#203]
It would be nice if a resource could be loaded asynchronously so that I could queue up a whole bunch of resources to be loaded, have them loaded in parallel, and then have the game start when they are all loaded. Currently, I have to do this myself.

It would also help to allow sounds to be played before they're finished loading, so that the game wouldn't need to lock up as it loads a large sound file.

**Comment by steffen-wilke** [comment]
I think the basic request of asynchronous loading has been implemented with #243 if I'm not mistaken. The topic of streaming a sound before it's fully loaded should be tracked separately. @TheRamenChef If you don't have any objections, I think we can close this issue.

**Comment by TheRamenChef** [comment]
Sound loading is already open as #244, so yeah, this can be closed.
