### ISSUE TITLE
Add tweening support

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#204]
We should support some sort of xml-exportable animations for sprites to make more vivid games.
I imagine a node-based graph editor in utiLITI from where you can save newly created animations and import existing ones into your project. 
To help you visualize the idea, this was inspired by this cool tweet I saw:
https://twitter.com/CodeManuPro/status/1075885060849582081?s=09

This should include the following features:
- graphs for scale (x and y separately, maybe), rotation, x and y position. All with respect to time. 
- each graph has a list of nodes, and a list of predefined easing curves for the segments between the nodes (apart from linear functions, there's a lot of possibilities for predefined curves. https://easings.net/de offers a few great examples.)
- possibility to export animations to xml files or add them to the .litidata file. 
- possibility to import animations from existing xml files
- preview animations on any sprite that's already in the project
- apply animations not only to sprites, but also to UI elements 

Since there is not really a need for this window to be pinned to the utiLITI main frame, we should just directly write it in JavaFX and include it as an "animations" tab once utiLITI is ported to JavaFX as well.

**Comment by steffen-wilke** [comment]
We should also existing existing freely available solutions for this. Maybe there is a general data format for such animations that we can support or adapt.

**Comment by nightm4re94** [comment]
As a more abstract approach, we could consider implementing or referencing a tweening framework.
Probably the most well-known Java Tweening framework is [Aurelien Ribon's Universal Tweening Engine](https://code.google.com/archive/p/java-universal-tween-engine/). With its permissive Apache 2.0 License, we could reference and tweak it to our needs. 
Downside: The project seems somewhat abandoned since 2012, but there is a [fork on GitHub](https://github.com/dorkbox/TweenEngine) which has addressed some open issues.

I think that tweening would be a sufficient, streamlined, and generally reusable approach to modify numeric values over time. In fact, the aforementioned Tweening engine implements every single [easing function defined by Robert Penner](http://robertpenner.com/easing/), which are available under BSD and MIT. In the end, we just need an interface that can be implemented by GUIComponents, Entities, Images, Sounds,... to modify their numeric attributes over time.

Building node-based animations might be nice in terms of individuality - but let's be honest: Such a feature, including the corresponding UI in utiLITI and import / export capabilities, is probably out of scope for LITIENGINE.

**Comment by nightm4re94** [comment]
I've managed to come up with a working prototype for tweening support using the suggested Tweening Engine. It looks very promising and was super easy to implement.

**Comment by nightm4re94** [comment]
#352 has added basic Tweening functionality which will be expanded upon as discussed in #353.
