### ISSUE TITLE
Resolve collision with map borders in the same way as collision with collision boxes.

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#205]
At the moment, movement is entirely locked once an entity collides with the map border. 
Instead, it should behave in the same way as just colliding with a regular collision box.

**Comment by TheRamenChef** [comment]
A kinda hackish solution would be to add collision boxes for the map border.

**Comment by nightm4re94** [comment]
Of course that's possible, but there's no reason why the map border should generally be treated differently from normal collision.
