### ISSUE TITLE
NullPointerException in Utiliti trying to load .litidata file

### ISSUE THREAD

**Issue by mttdbrd** [gurkenlabs/litiengine#216]
Whenever I try to `gradlew run` utiliti the game crashes.

Here's the output: 

> Feb 03, 2019 8:16:25 AM de.gurkenlabs.litiengine.configuration.Configuration loadFromFile
> INFO: Configuration config.properties loaded
> Feb 03, 2019 8:16:27 AM de.gurkenlabs.litiengine.DefaultUncaughtExceptionHandler uncaughtException
> SEVERE: Game crashed! :(
> java.lang.NullPointerException
>         at de.gurkenlabs.utiliti.EditorScreen.render(EditorScreen.java:137)
>         at de.gurkenlabs.litiengine.graphics.RenderComponent.render(RenderComponent.java:154)
>         at de.gurkenlabs.litiengine.RenderLoop.run(RenderLoop.java:23)

This is the line that's failing: 
`      Program.getTrayIcon().setToolTip(Game.info().getName() + " " + Game.info().getVersion() + "\n" + this.currentResourceFile + mapName);
`

Any line that calls getTrayIcon() and doesn't test for null also fails. I can submit a pull request to fix if you like.

I'm running this on Fedora 29 with Gnome 3, so I'm wondering if getTrayIcon() is returning null. This happens on the master branch and on the 0.4.15-alpha branch.

Confirmed by running in debug mode in IntelliJ. Here's a screenshot showing that getTrayIcon() returns null.
![screenshot from 2019-02-03 08-29-24](https://user-images.githubusercontent.com/10905253/52179329-f3765000-278d-11e9-928c-07e63a80062d.png)

**Comment by steffen-wilke** [comment]
@mttdbrd Many thanks for the detailled bug report.
