### ISSUE TITLE
Introduce a SoundSource Entity

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine#217]
We need to specify what should be configurable via the entity:

- volume
- distance
- loop
- "PlayMode" (on collision? on demand(method call)? on entity message? loop)

- [x] Introduce new `MapObjectType.SOUND` 
- [x] Introduce `SoundSource` entity
- [x] Add utiLITI controls to add Sound MapObjects to the environment.

This is related to #67 which targets the general resource management of `Sound` resources.

**Comment by nightm4re94** [comment]
The audible distance of a SoundPlayback is currently dictated globally by the SoundEngine's maxDistance. We would need to introduce individual falloff ranges for SoundPlaybacks first.
