### ISSUE TITLE
Use Clips instead of SourceDataLines

### ISSUE THREAD

**Issue by TheRamenChef** [gurkenlabs/litiengine#219]

**Comment by steffen-wilke** [comment]
As far as I remember, we used `Clips` in a very early version of the engine and there where some Java side limitations on parallel playback of clips, i.e. max sounds that could be played in parallel which was the reason to switch to `SourceDataLines` in the first place.
I need to check that though, this dates way back to even before the engine was on GitHub I think.

@TheRamenChef Are there any particular benefits, that we cannot solve with `SourceDataLines` right now?

**Comment by TheRamenChef** [comment]
On further research, I don't think this should be done.
