### ISSUE TITLE
Support isometric maps.

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#225]
Title says it all. We need an Isometric Map Renderer as well as the tile detection logic for isometric tiles.

https://gamedevelopment.tutsplus.com/tutorials/creating-isometric-worlds-a-primer-for-game-developers--gamedev-6511

**Comment by TheRamenChef** [comment]
I was going to implement an isometric map renderer in my upcoming overhaul. Stay tooned.

**Comment by steffen-wilke** [comment]
@TheRamenChef That's great. Do you have any rough ETA on this? I'm currently planning out the next versions and I want to incorporate this feature.

**Comment by TheRamenChef** [comment]
I'll probably have it by the end of next week.
