### ISSUE TITLE
utiLITI: copy / pasting creatures

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#235]
In utiLITI, when a copy of an creature already placed is made, the ID changes and the sprite is changeable without unexpected modifications.
But, in-game, when the map containing those creatures is loaded, they all appear with exactly the same sprite, although it was changed after copy/pasting under utiLITI.

**Comment by CalvinMT** [comment]
I just looked into the ".litidata" file with a text editor and found out that the value of the creatures previously copy/pasted did not change. That is why sprites are the same in-game.
I'm guessing that the value is therefor not updated when selecting a sprite, unless a new creature is created in utiLITI with the tool "Add Creature".

**Comment by nightm4re94** [comment]
Thanks for letting us know!
