### ISSUE TITLE
Fix MapObject import for Objects created with external programs.

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#237]
When re-importing a map into an existing project that has been changed by adding MapObjects, the new MapObjects are not always loaded. Maybe an ID assignment problem again?

This has been brought up [in our forum](https://forum.litiengine.com/d/45-utiliti-how-to-avoid-adding-the-same-elements-after-impoting-the-same-map).

**Comment by steffen-wilke** [comment]
See #240
