### ISSUE TITLE
utiLITI 0.4.15-alpha fails to load .tmx file created by Tiled 

### ISSUE THREAD

**Issue by AdrianLeeElder** [gurkenlabs/litiengine#239]
I am unable to load a .tmx file using utiLITI v0.4.15-alpha, created by Tiled (tried with v1.1.6 and 1.1.5, and the latest 1.2.3). 

In the utiLITI, this is what's in my console:

```
SEVERE    Game crashed! :(
INFO      c:\users\adrian\checkers\src\main\resources\board.tmx\images\0.png could not be found.
```

My .tmx file contains two layers, one for the actual tiles, and another for the background image (0.png). For some reason, when importing the .tmx file it's looking for the image file _inside_ of the board.tmx file?

![image](https://user-images.githubusercontent.com/4062150/54648056-40329380-4a7b-11e9-88aa-15ce493b0b1e.png)

**Comment by TheRamenChef** [comment]
TMX overhaul part 2 is in the pipeline, and this issue will most likely be fixed by it.

In the meantime, would you mind showing the actual XML element for the image layer? It would help debug the propblem if we can see the bad data that's being passed in.

**Comment by AdrianLeeElder** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0" tiledversion="1.1.5" orientation="orthogonal" renderorder="right-down" width="8" height="8" tilewidth="96" tileheight="96" infinite="0" nextobjectid="1">
 <layer name="Tile Layer 1" width="8" height="8">
  <data encoding="csv">
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0
</data>
 </layer>
 <imagelayer name="Image Layer 1">
  <image source="../../../../../0.png" width="1366" height="768"/>
 </imagelayer>
</map>
```

I'm new to the tmx file format, I didn't even realize it was xml based. I tried changing the path to ../0.png or 0.png with the same result.

**Comment by TheRamenChef** [comment]
#243 has been merged, with what I'm hoping fixes your problem. Does it work with the latest snapshot?

**Comment by steffen-wilke** [comment]
I just checked the above example and with an image in the expected folder (5 folders up) I didn't have any issue opening the map in utiLITI with the editor's current version.

@AdrianLeeElder Thank's for the detailed report.
