### ISSUE TITLE
Improve force handling by aggregating all forces before applying

### ISSUE THREAD

**Issue by gurkenlabs** [gurkenlabs/litiengine#24]
When forces are active on a `IMovableEntity`, they are being applied by its `MovementController` implementation.

Currently this is implemented such that all forces individually:

```java
for (final Force force : this.activeForces) {
...
final double angle = GeometricUtilities.calcRotationAngleInDegrees(collisionBoxCenter, force.getLocation());
final boolean success = this.getPhysicsEngine().move(this.getEntity(), (float) angle, gameLoop.getDeltaTime() * 0.001f * force.getStrength());
```

This should be refactored ot only call `this.getPhysicsEngine().move(this.getEntity(), ...` once and aggregate all the forces before.

**Comment by steffen-wilke** [comment]
At some point in the future, we might need to revisit the "force" implementation overall. Slightly improving the current implementation (if even), is not the main focus of our development.

**Comment by nightm4re94** [comment]
It is I, the man from the future.
