### ISSUE TITLE
Can't load anything with the Spring release (v0.4.16-alpha)

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#245]
I can't launch my game with litiengine v0.4.16-alpha. And I cannot open the ".litidata" file, nor can I open any of the ".tmx" files with utiLITI v0.4.16-alpha.
Everything was readable/launchable with the Nukem release (v0.4.15-alpha).

For debugging, here's the error for my program: [crash.txt](https://github.com/gurkenlabs/litiengine/files/3029173/crash.txt).
Line 355 of the MenuScreen class:
`Image frameImageHovered = (Image) Resources.spritesheets().get("frame_" + this.worldSelect.getName().toLowerCase() + "_hovered").getImage();`
First time loading from Resources in "Prepare()" method.
Resources.load() is called in "initializeComponents()".

And here's the error for utiLITI (no need for file upload for this one):
> main threw an exception:
java.lang.NullPointerException
	at de.gurkenlabs.utiliti.components.EditorScreen.load(EditorScreen.java:306)
	at de.gurkenlabs.utiliti.Program.main(Program.java:145)

As said earlier, everything worked fine with the previous release (v0.4.15-alpha). So I'm guessing they've been some changes in the ".litidata" file structure.

**Comment by steffen-wilke** [comment]
@CalvinMT Could you attach your `.litidata` file for better troubleshooting?

**Comment by TheRamenChef** [comment]
Found it. `tiles` was null, probably because the tileset didn't add any special properties to them, it tried to iterate over it anyway, `NullPointerException` was thrown, tileset failed to load. Fixed.
