### ISSUE TITLE
Investigate the issue of glitching though very small collision boxes

### ISSUE THREAD

**Issue by gurkenlabs** [gurkenlabs/litiengine#25]
If an entity moves fast enough, it is currently possible to glitch though small collision boxes. 
This needs to be investigated and fixed.

**Comment by gurkenlabs** [comment]
I think we could implement a multisamling approach as described here:
http://www.metanetsoftware.com/technique/tutorialA.html#section5

**Comment by steffen-wilke** [comment]
We already have a simple approach for that. This is only an issue in very rare edge cases and should not be the focus of our development for now.
