### ISSUE TITLE
Setting "drawTextShadow" to "true" on GUIComponents crashes  the game

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#260]
In GUIComponent.renderText(), the TextRender's renderWithOutline()-method is called, but the Text Antialiasing rendering hint (set in the GUIComponent's appearance) is incompatible with the global antialiasing hint. (renderWithOutline creates a shape from Text to display an outline. To render the shape with antialiasing, RenderingHints.KEY_ANTIALIASING is set to the antialiasing parameter passed to the method. This will fail.)

**Comment by steffen-wilke** [comment]
Fixed with 511d0b8a40458a33d2b7e2d7a9a028c7a5b0ff30
