### ISSUE TITLE
utiLITI: exporting map with wrong tileset location (v0.4.17-alpha)

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#264]
When exporting a map from utiLITI, the tileset's location (.tsx) isn't considered as being right when the exported map is opened through Tiled.
I'm guessing Tiled doesn't support rooted locations for tilesets.

**Comment by TheRamenChef** [comment]
What is the location being saved as, and what should it be saved as in order for Tiled to open it?

**Comment by CalvinMT** [comment]
I tried exporting again to use as an example, but it's fine. It must have done that the first time because of the version change.
I should've checked more than once, as I usually do. My bad.

**Comment by TheRamenChef** [comment]
What version change? What does it have to do with anything?

**Comment by CalvinMT** [comment]
Forget my last comment. I was mistakenly using an older version of utiLITI (v0.4.16.1-alpha).

At line 3 in the ".tmx" file, there's this:
`<tileset firstgid="1" source="file:/C:/Users/CalvinMT/Desktop/maps/map_0.tmx"/>`
Instead of, in my case, something like this:
`<tileset firstgid="1" source="C:/Users/CalvinMT/Desktop/maps/map_tiles.tsx"/>`

I deepened my research and found that:

- `file:/` shouldn't be added at the beginning of source.
- The name and extension is wrong. I believe that the name of the map being exported is used instead of the ".tsx" file name.

**Comment by TheRamenChef** [comment]
This is what I get for not writing a unit test for the `URLAdapter`.

I fixed the issue with the wrong file name being written, though I still need to fix the issue of the full path being written out. I don't have time for that ATM, though.
