### ISSUE TITLE
utiLITI windows scaling issues

### ISSUE THREAD

**Issue by profiluefter** [gurkenlabs/litiengine#275]
If I open utiLITI on my 4k monitor, the tiles of a map get scaled but the grid doesn't and weird rendering issues appear. 
<img width="507" alt="standard behavior" src="https://user-images.githubusercontent.com/18028031/59946903-22a30a80-946c-11e9-9078-8ae820be7998.png">
A workaround to get it working is to let windows handle the scaling. This is done via the compatibility settings by selecting system as a scaling mode. The downside of this workaround is that the UI gets blurry.

**Comment by nightm4re94** [comment]
Thanks for reporting this!

**Comment by nightm4re94** [comment]
Sorry, can't test without having a 4k monitor at my disposal :/ anyone else?

**Comment by profiluefter** [comment]
I can test builds for you but I currently don't have time to look into the source code or something like that

**Comment by steffen-wilke** [comment]
Just to track this: WQHD (2560 x1440) works fine.

**Comment by nightm4re94** [comment]
While working on my Laptop with FullHD resolution, I also encountered this issue (and it persists, no matter which game project I edit).
The rendering of the Tiles is misaligned from the actual grid, as you can see in the screenshot below:
![grafik](https://user-images.githubusercontent.com/26114385/74193438-aad25c00-4c57-11ea-9491-1dc1e01bd5b9.png)
If I zoom out more, the offset increases.

**Comment by nightm4re94** [comment]
Today we have been able to reproduce the issue on my laptop:
When using the built-in Windows scaling feature (for readability on small screens), the Entity bounding boxes are rendered with an offset.
Can you confirm this as the reason for the issue? Try messing around with Windows scaling settings and see if the problem still occurs.

**Comment by profiluefter** [comment]
Monitor scaling 100%:
![100%](https://user-images.githubusercontent.com/18028031/79670773-b9903e80-81c5-11ea-90be-0d870fcfc24d.png)
Monitor scaling 150%:
![150%](https://user-images.githubusercontent.com/18028031/79670799-e9d7dd00-81c5-11ea-99bf-82b8dd2a9424.png)
Monitor scaling 200%:
![200%](https://user-images.githubusercontent.com/18028031/79670819-02e08e00-81c6-11ea-86ce-d116bb0668ad.png)

So I'm pretty sure this is the reason for this issue, yes.

**Comment by nightm4re94** [comment]
Thanks for checking it out! We may already have a lead on this, but oddly this doesn't seem to happen on all hardware.

**Comment by steffen-wilke** [comment]
Update: This issue is related to the installed/used JDK version. It works as expected for up until **Java 8** (tested with `jdk1.8.0_201`). 
The problem occurs, starting with **Java 9** and above. Tested with `jdk-9.0.4`, `jdk-11.0.2`, `jdk-13.0.2`

**Comment by steffen-wilke** [comment]
Possibly related to HiDPI support, implemented with Java 9:
[JEP 263: HiDPI Graphics on Windows and Linux](https://openjdk.java.net/jeps/263)

see also: jfree/jfreechart#170

**Comment by steffen-wilke** [comment]
Starting with Java9, the implementation defines a default transformation for the `Graphics2D` object to support HighDPI settings:

### JAVA 9:
![image](https://user-images.githubusercontent.com/7015370/106389072-bcb98b80-63e1-11eb-9263-2ebc83434341.png)

### JAVA 8
![image](https://user-images.githubusercontent.com/7015370/106389105-fb4f4600-63e1-11eb-9c97-e3247f3f5d91.png)

When rendering Shapes we overwrite the default `AffineTransform` of the `Graphics2D` object:

https://github.com/gurkenlabs/litiengine/blob/0af15618018744f7c9d832fe98a7e91210b465a1/src/de/gurkenlabs/litiengine/graphics/ShapeRenderer.java#L73-L76
