### ISSUE TITLE
TravisCI builds breaking with oraclejdk11

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#278]
TravisCI downloads the OracleJDK from oracles website.
I noticed oraclejdk11 isn't available for download on the site anymore ([Java SE Development Kit 11](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html)) and that's why TravisCI builds are breaking.

Because OpenJDK and OracleJDK are virtually the same, I'd suggest to use openjdk11 for TravisCI instead.

**Comment by steffen-wilke** [comment]
gotta love Oracle...

**Comment by steffen-wilke** [comment]
Fixed with 14c712b076c90ac0553683da48f77fdd9bea97b2
