### ISSUE TITLE
Add boolean visibility control over entities

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#280]
As @steffen-wilke suggested in [this conversation](https://forum.litiengine.com/d/70-invisible-cursor-props-and-entities) on the forum:

> I think we should extend the base Entity class such that it has a visible property. However we need to be careful about this and check for all the places that might render an entity in the engine and include a check accordingly.
> 
> Suggested API
> ```myprop.setVisible(false);```
> ```mycreature.setVisible(false);```

**Comment by steffen-wilke** [comment]
see 14c26df15351832706d0bca3c0f22c16a14d5388
