### ISSUE TITLE
Resolution is set on window's size instead of window's content

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#286]
When the resolution is automatically loaded and set from config.properties, the engine sets the loaded values to the window's size instead of the window's content's size (i.e.: the frame of the window).
Example:

```
// In config.properties
gfx_resolutionHeight=720
gfx_resolutionWidth=1280

// In main() method
Game.init();
System.out.println(Game.window().getResolution());

// In console
INFO: Configuration config.properties loaded
java.awt.Dimension[width=1264,height=681]
```

**Comment by steffen-wilke** [comment]
The recent changes from 1835b02b3fd7bc32625db67c5f11bc074c8c77f9 also fix this issue.
