### ISSUE TITLE
Fullscreen borderless mode

### ISSUE THREAD

**Issue by Technerder** [gurkenlabs/litiengine#290]
Does this engine provide a method to make the game full-screened yet borderless?

**Comment by nightm4re94** [comment]
Hi there, do you mean borderless windowed mode in full screen size? Like in [this example](https://www.howtogeek.com/324835/how-to-play-any-windows-game-in-full-screen-borderless-windowed-mode/)?

**Comment by Technerder** [comment]
Precisely

**Comment by steffen-wilke** [comment]
Now we support it :)

To use it, just set the option `gfx_displayMode=BORDERLESS` in the `config.properties` or use `Game.config().graphics().setDisplayMode(DisplayMode.BORDERLESS)` from code before initializing the game.

**Comment by Technerder** [comment]
Awesome!
