### ISSUE TITLE
Add sprite file export capability

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#293]
It would be nice to be able to export all spritesheet information for the current utiLITI project. This way, you could batch import your sprites to a new project without having to copy-paste bits of the game resource file.

**Comment by YannikSchoeberl** [comment]
What kind of file format do you think of to export the spritesheet information?

**Comment by nightm4re94** [comment]
Currently, we use [sprite info files (see docs)](https://docs.litiengine.com/basics/resource-management/sounds-and-music/sprite-info-files), which are originally based on the output format of [this Photoshop Spritesheet Export script](https://github.com/bogdanrybak/spritesheet-generator). 
This mechanism is a relic from the very early days of LITIengine, but it is still sometimes useful for batch-importing sprites.
