### ISSUE TITLE
TextFieldComponent doesn't render \n

### ISSUE THREAD

**Issue by AZ-0** [gurkenlabs/litiengine#294]
I needed the user to input some text, and this text was allowed to be multiline. Since the `TextFieldComponent` implementation doesn't let anyone continue typing when pressing enter, I added this little bit of code :
```java
this.result.onChangeConfirmed(s ->
{
	this.result.setText(s + "\n.");
	this.result.setSelected(true);
});
```
where `this.result` is the said TextFieldComponent.

However at this point it wouldn't let me render the `\n` character, here is the little screen:
![image](https://user-images.githubusercontent.com/35401882/69669722-b4a1e580-1092-11ea-882c-efe879fa4a7d.png)

Additionally, it seems that there is no full compatibility with azerty keyboards, as some keys don't do anything and some others display the wrong character x)

**Comment by TheRamenChef** [comment]
`TextFieldComponent` isn't intended as a multiline input.

**Comment by AZ-0** [comment]
Thanks for your reply :D
In fact, I found after a little bit of testing that ImageComponent don't render \n as well, and seeing as they deleguate the rendering to GUIComponent I fear they don't either :c
I'll test with some when I have the time 😁
