### ISSUE TITLE
Cursor offset added backwards

### ISSUE THREAD

**Issue by KvaGram** [gurkenlabs/litiengine#296]
The value of the cursor offset is inverted twice when setting a cursor.
It is done at RenderComponent.render()
at line 169
and at RenderComponent.setCursor()
at lines 215,216

code-lines are according to version 0.4.17.

As a result, the offset are applied wrong.

**Comment by nightm4re94** [comment]
This is no longer an issue since the Cursor is no longer part of the RenderComponent (since 172c9df8060adab8c8695bd6015bb8d20bdbe6af)
