### ISSUE TITLE
Fix Emitter editing

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine#298]
Currently, the dialog that allows editing emitters in the utiLITI editor has some major issues:

![image](https://user-images.githubusercontent.com/7015370/71545846-510c2000-2990-11ea-8762-4a475cb4effa.png)

* UI-wise the elements are misaligned and some are not fully readable (see screenshot) this makes the UI hard to use and understand
* When trying to create a new emitter from scratch in the editor, this doesn't seem to be possible at the moment; at least I wasn't able to get a visible result.
  * Some investigations showed, that a lot of `ParticleParameters` are not serialized properly (maybe unchanged values, especially the max values are not set as custom property?)
* I would say that this feature is **entirely broken** right now, unless you have an already working emitter and just want to tweak some numbers.
* When adding a new emitter, we should define appropriate default values so the user can already see something

![image](https://user-images.githubusercontent.com/7015370/71545806-b14e9200-298f-11ea-973a-f670db28b575.png)

We might also think about integrating these settings from the separate modal dialog to the normal `PropertyPanel` in order to enable live feedback on the changes in the editor and reduce the friction to play around with `Emitter` settings. 
Alternatively, there should be at least a preview of the emitter in the modal dialog.

**Comment by nightm4re94** [comment]
Some more requirements:
- [ ] Exporting Emitters as xml
- [ ] Making Custom Emitters usable as EntityEmitters

**Comment by nightm4re94** [comment]
To make the whole editor component less overwhelming, we could consider an approach similar to Unity's [Particle System Modules](https://docs.unity3d.com/Manual/ParticleSystemModules.html), where you can toggle behaviours such as velocity over lifetime / size over lifetime separately.

**Comment by nightm4re94** [comment]
In my [recent Branch](https://github.com/gurkenlabs/litiengine/tree/EmitterPanelRevision), I am redesigning the Emitter modification process in utiLITI from scratch.

**Comment by nightm4re94** [comment]
The new panel also needs to contain controls for particle rotation as requested per #345 .
