### ISSUE TITLE
The library's jar has a misleading module-info.class file.

### ISSUE THREAD

**Issue by jeuxjeux20** [gurkenlabs/litiengine#304]
It is currently impossible to use LITIEngine with Java 13, using the modular system, as the jar file contains a misleading `module-info` in it, describing the `java.xml.bind` module:
```
java.xml.bind jar:file:///D:/WhereverMyJarIs/litiengine-0.4.18.jar/!module-info.class
exports javax.xml.bind
exports javax.xml.bind.annotation
exports javax.xml.bind.annotation.adapters
exports javax.xml.bind.attachment
exports javax.xml.bind.helpers
exports javax.xml.bind.util
requires java.activation transitive
requires java.base mandated
requires java.desktop
requires java.logging
requires java.xml transitive
uses javax.xml.bind.JAXBContextFactory
```

Unfortunately this makes the module system threat the `litiengine.jar` file as the `java.xml.bind` module.

A solution would be to **remove the `module-info.class` file from the jar artifact**, to be able to use it as an automatic module, so it can be used like that:
```java
module com.myproject {
    require litiengine; // It currently throws 
}
```

([See StackOverflow post](https://stackoverflow.com/questions/59809594/how-to-force-using-a-jar-as-an-automatic-module-without-editing-it))

**Comment by namannigam** [comment]
To add to it, this seems to have been introduced with some packaging library/plugin since the `module-info.class` is a replica of the `java.xml.bind` modules's descriptor class file copied onto the path of this artifact.
