### ISSUE TITLE
Environment.add overload is unrelated

### ISSUE THREAD

**Issue by Phlosioneer** [gurkenlabs/litiengine#310]
Environment.add(IEntity) loads an entity, adds it to various lists depending on the entity type, and fires various events.

Environment.add(IRenderable, RenderType) adds an object to the associated Collection<IRenderable>.

They are named the same and do completely different things. It's especially annoying when the IEntity implements IRenderable, leading to code like this:
```java
var myLight = new LightSource(...);
Game.world().environment().add(myLight);
Game.world().environment().add(myLight, RenderType.NORMAL);
```
(Note: this issue is not specific to LightSource, it's just the easiest example)

I would recommend making the method names more descriptive; something like "addEntity" and "addRenderable"?

**Comment by TheRamenChef** [comment]
You don't need to add a renderable entity to the environment as an `IRenderable` for it to be rendered.

**Comment by steffen-wilke** [comment]
> You don't need to add a renderable entity to the environment as an `IRenderable` for it to be rendered.

That's correct.

If an `Entity` implements the `IRenderable` interface, the `render` method gets called automatically by the `RenderEngine.renderEntity` method which is implicitly used by the `Environment`.

> They are named the same and do completely different things.

Basically both methods add something to the environment. Yes, adding an entity is more complex than adding an `IRenderable` instance but the purpose is still the same: "Add whatever I provide as a parameter to the environment". 

```java
// add a custom renderable implementation that should be rendered with RenderType.NORMAL
IRenderable myRenderable = new CustomRenderable(...);
Game.world().environment().add(myRenderable, RenderType.NORMAL);

// add anonymous rendering
Game.world().environment().add(g -> {
    // do some custom rendering
}, RenderType.NORMAL);
```
The API here is designed to have a simple and easy to remember syntax for prevalent calls. Naming the method `addEntity` and passing an `Entity` instance is kind of redundant and slightly clutters up the API. But I think this discussion could really go either way depending on the point of view.

However, I also think the Javadocs of these methods need improvement to better indicate their purpose.
