### ISSUE TITLE
Consider switching console Font

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#311]
I have recently grown very fond of [Fira Code](https://github.com/tonsky/FiraCode), a nice monospace font with coding ligatures. Therefore I want to suggest using it as utiLITIs console font. Standard letters look much similar to Consolas, which I also like and which is currently in use. However, the Ligatures (equality signs, arrows,... ) ensure more mathematical correctness and readability. See examples below (left side).
![Fira Code ligatures ](https://raw.githubusercontent.com/tonsky/FiraCode/master/showcases/all_ligatures.png)

Let me know what you think about this!

**Comment by TheRamenChef** [comment]
I mean, we could just as easily use the proper special characters in the UtiLITI console.

**Comment by nightm4re94** [comment]
...which would imply having to copy-paste unicode characters from external resources when writing something as trivial as inequality.

**Comment by TheRamenChef** [comment]
Or use the escape sequence:

  - `\u2260` &rarr; &ne;
  - `\u2264` &rarr; &le;
  - `\u2265` &rarr; &ge;

Anyway, I'm not sure how much this actually matters, since the font was made for source code, not consoles.

**Comment by nightm4re94** [comment]
I am aware of escape sequences. Do you know all of them by heart? 
When discussing this with Steffen, we agreed that these ligatures are a matter of personal preference in code editors, but when outputting information for the end user, they would be a nice addition to maintain human-readability.
