### ISSUE TITLE
What is g?!

### ISSUE THREAD

**Issue by umocolombo** [gurkenlabs/litiengine#316]
Very sorry my stupid question. But what is "g". 
How i can print simple text?! And where in docs this described?!

import de.gurkenlabs.litiengine.Game;

```
public class test1 {
    public static void main(String[] args) {

        Game.graphics().renderText(g, "my text", 50, 100);
        
    }

}
```

**Comment by TheRamenChef** [comment]
`g` is the graphics context that will be used to actually draw the text you sent to that method. The entry point method won't get one, nor should it. Instead, you need to initialize the render loop (this will be done when you initialize the engine) and give it something to draw, such as a screen. It will automatically call a `render` method in that object, which provides a graphics context that it can use.

Here's how you should do this:

    public class Test {
        public static class MyScreen extends Screen {
            public MyScreen() {
                super("screen");
            }

            @Override
            public void render(Graphics2D g) {
                Game.graphics().renderText(g, "my text", 50, 100);
            }
        }

        public static void main(String[] args) {
            Game.init(args);
            Game.start();
            Game.screens().display(new MyScreen());
        }
    }

**Comment by nightm4re94** [comment]
Also, you should consider that there are two ways to render text (or anything, really):

- ```Game.graphics().renderText(g, "my text", 50, 100);```
  This calls the RenderEngine to draw something within the game world (As if you would write on the floor)
- ```TextRenderer.render(g, "my text", 50, 100);```
  This is the proper way to render something GUI-related, because you just want it to be relative to the screen, not the game world.

**Comment by umocolombo** [comment]
thank you!
Your are magics!!!
ps sorry for the my stupid
