### ISSUE TITLE
Browser Frontend

### ISSUE THREAD

**Issue by ghost** [gurkenlabs/litiengine#319]
I'm curious to know if it's been considered writing a front end for the browser, so that games can be played online. This would bring games to the browser easily and (possibly) to the Nintendo Switch.

We're currently planning on implementing this using TeaVM and creating an abstraction layer for interacting with AWT or WebGL as well as XML readers for the tile set and tile map data from Tiled. Is this something feasible for this game engine? It's the only reason we're not considering it so far.

**Comment by tay10r** [comment]
Edit: I misspoke, we're using code generators for the tile sets and tile maps, they're not part of an abstraction layer.

**Comment by steffen-wilke** [comment]
What a coincidence: Last weekend, I actually experimented with TeaVM and JWebAssembly. While I was able to start a game with the engine (resources and game infrastructure were loaded), I didn't see any visual results yet. I think it might have to do with the way we render stuff (`Canvas`/`Bufferstrategy`).  So far, I didn't investigate this any further. 

> Is this something feasible for this game engine

It would be awesome to get the engine running in the browser via WebAssembly while still maintaining its plain Java nature. At the very least, it might be an experimental feature that we could expand upon.

**Comment by tay10r** [comment]
Last I checked, it didn't seem like TeaVM supported AWT containers, and instead used HTML directly. Was I wrong in this regard?

We use Canvas/BufferStrategy but made an interface replacement for Graphics so that we could also use a WebGL renderer.
