### ISSUE TITLE
Branch builds always fail in my repository

### ISSUE THREAD

**Issue by Gamebuster19901** [gurkenlabs/litiengine#333]
It appears that Travis always fails to build litiengine if it's building a branch that is not on this repository. It still works for pull requests in other repositories though.

Here is a relevant build failure: https://travis-ci.com/github/Gamebuster19901/litiengine/builds/158551786

Here is an image showing that the pull request build succeeds but the branch build fails:
![image](https://user-images.githubusercontent.com/7155747/78513307-994d9200-7778-11ea-91b7-90825167c017.png)

**Comment by steffen-wilke** [comment]
I also noticed that. I think it's due to missing Sonarcloud credentials. Maybe we can find a way to deactivate the sonar scanner for remote origins.

**Comment by TheRamenChef** [comment]
I think a better solution overall would be to have the build pass even if the sonar scanner fails.

**Comment by Gamebuster19901** [comment]
This issue has resurfaced with github actions.

![image](https://github.com/user-attachments/assets/f7c47caa-5439-46ee-9678-b4e391557b40)

**Comment by nightm4re94** [comment]
I'll check it out, thanks.

**Comment by Gamebuster19901** [comment]
Just a note, this issue was causing the build failures to spam my email, so I just disabled github actions entirely for my repo.

![image](https://github.com/user-attachments/assets/17b681f5-9023-49e3-ba55-419b26885e1d)

**Comment by nightm4re94** [comment]
Sorry! My free time is super packed currently, but I hope to find some time for this soon.

**Comment by nightm4re94** [comment]
Hi @Gamebuster19901 , could you please check if the issue was fixed by [this commit](https://github.com/gurkenlabs/litiengine/commit/77d820eb13de9ec44d94ec38dbb3fab83e607682)?

**Comment by Gamebuster19901** [comment]
Issue is resolved.
