### ISSUE TITLE
Add TextRenderer overloads

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#343]
- [x] text with outlines AND Align / VAlign parameters
- [x] text with line breaks AND Align / VAlign parameters

**Comment by TheRamenChef** [comment]
I added some overloads for those. Do they work the way they should for `Align.CENTER_LEFT` and similar settings?

**Comment by nightm4re94** [comment]
Thanks, will check it out this weekend!

**Comment by nightm4re94** [comment]
Some tests:

- [ ] Aligned text with linebreaks, but the text is so short it doesn't need any linebreaks.
![grafik](https://user-images.githubusercontent.com/26114385/82161259-865fce80-989b-11ea-9876-411378444a00.png)

- [ ] Aligned text with linebreaks, **LEFT** align, **TOP** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161645-c96f7100-989e-11ea-88bd-b799c6ffbf57.png)

- [ ] Aligned text with linebreaks, **LEFT** align, **MIDDLE_TOP** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161752-a5f8f600-989f-11ea-8fd3-3a1686414545.png)

- [ ] Aligned text with linebreaks, **LEFT** align, **MIDDLE** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161659-e3a94f00-989e-11ea-83c9-0f9a575aaae8.png)

- [ ] Aligned text with linebreaks, **CENTER_LEFT** align, **MIDDLE** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161683-0b98b280-989f-11ea-9207-df5a6ec73123.png)

- [ ] Aligned text with linebreaks, **CENTER** align, **MIDDLE** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161690-1f441900-989f-11ea-853a-6a6f35e01e2e.png)

- [ ] Aligned text with linebreaks, **CENTER_RIGHT** align, **MIDDLE** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161708-3c78e780-989f-11ea-92f0-f3ce4e387778.png)

- [ ] Aligned text with linebreaks, **RIGHT** align, **MIDDLE** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161716-4bf83080-989f-11ea-8ad7-6b2349627573.png)

- [ ] Aligned text with linebreaks, **JUSTIFY** align, **MIDDLE** valign.
![grafik](https://user-images.githubusercontent.com/26114385/82161726-67633b80-989f-11ea-964d-d50046374c60.png)

for reproduction:
```java
    double x = Game.window().getWidth() * 1 / 8d;
    double width = Game.window().getWidth() * 6 / 8d;
    double y = Game.window().getHeight() * 1 / 4d;
    double height = Game.window().getHeight() * 2 / 4d;
    g.setColor(Color.white);
    g.drawRect((int) x, (int) y, (int) width, (int) height);
    for (Align align : Align.values()) {
      if (align == Align.JUSTIFY) {
        continue;
      }
      for (Valign valign : Valign.values()) {
        TextRenderer.renderWithLinebreaks(g,
            String.format("H: %s V: %s", align.name().toLowerCase(), valign.name().toLowerCase()), align, valign, x, y, width, height, true);
      }
    }
    TextRenderer.renderWithLinebreaks(g, Resources.strings().get("linebreaktest"), Align.LEFT, Valign.MIDDLE_TOP, x, y, width, height, true);
```
where
```
linebreaktest=Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

**Comment by TheRamenChef** [comment]
I can't reproduce this. Can you show more details about your configuration (in particular, the window size)?

Also, is it aligned the way it should for other lines? Should there be space to the left of the lines for `CENTER_LEFT`?

**Comment by nightm4re94** [comment]
Of course, here's my gfx configuration:
```
gfx_displayMode=WINDOWED
gfx_enableResolutionScale=true
gfx_resolutionHeight=900
gfx_resolutionWidth=1600
```

**Comment by TheRamenChef** [comment]
That seems like useless behavior. Why not just use one of the main alignments and reduce the wrap width for that?

My interpretation of `CENTER_LEFT` and `CENTER_RIGHT` was as a "middle ground" between center align and either left or right align, using the mean position between them. The `Align` and `Valign` classes don't quite use the proper implementation for this (which, incidentally, was causing the bug), and I was wondering if the difference was intentional.

**Comment by nightm4re94** [comment]
Could you please illustrate the behaviour you described so we are on the same page here?
I haven't tested the other implementation yet. Were you able to reproduce the issue I had?

**Comment by nightm4re94** [comment]
Both cases seem to work as intended now.
