### ISSUE TITLE
Tile map not loading

### ISSUE THREAD

**Issue by PotaytoPrograms** [gurkenlabs/litiengine#350]
**Describe the bug**
When ever I try to load a .tmx file the window freezes and I cant interact with it in any way. I load the file using **Maps -> Load Map**. I have already loaded the tileset before I loaded the map.

**Stack Trace**
I cant get a stack trace because the window freezes

**To Reproduce**
simply load a .tmx file.

**Expected behavior**
The map to load properly and be shown.

**System:**
 - OS: Ubuntu
 - LITIENGINE version: 0.5.0-beta

**Comment by steffen-wilke** [comment]
Could you possibly provide a sample tmx file to reproduce the issue? Loading maps in general works, I think this might have something to do with your particular map.

**Comment by steffen-wilke** [comment]
possibly related to #269

**Comment by Gamebuster19901** [comment]
This is #374
