### ISSUE TITLE
Game window zoom,  grid  line issue

### ISSUE THREAD

**Issue by arisosoftware** [gurkenlabs/litiengine#351]
**Describe the bug**
The special screen zoom ratio causes rendering problems: grid lines are displayed and should not be.

**Stack Trace**
no error

**To Reproduce**
1. Execute the sample project 
2. Adjust the windows size make it a little small
3. See error: some grid line show.

**Expected behavior**

no grid line displayed when end user zoom in or zoom out the game screen

**Screenshots**
`<img src="https://ibb.co/HBkzsWq" >`
![image](https://user-images.githubusercontent.com/21161938/97382379-a8756800-18a1-11eb-9cad-46c4849a5b4e.png)

**Your System:**
 - OS:  UBUNTU 18.04
 - LITIENGINE version:  0.5.0-beta
 - Screen resolution: 1920x1080

**Additional context**

**Comment by TheRamenChef** [comment]
Where is the sample project?

**Comment by arisosoftware** [comment]
it's
https://github.com/gurkenlabs/litiengine-gurk-nukem 
Oh, you mean I should create this question in the sample project instead of the engine?
I think the workaround solution should be to adjust the display ratio algorithm to ensure that there is no problem with the float calculation.

**Comment by nightm4re94** [comment]
The render scale has been adjusted in the meantime and this issue could not be reproduced.
