### ISSUE TITLE
Correct speed when moving diagonally

### ISSUE THREAD

**Issue by ghost** [gurkenlabs/litiengine#354]
**Describe the bug**

Movement does not seem(?) to be normalized when moving diagonally compared to the other directions (up, left, down right).

**To Reproduce**

Create a basic entity with the built-in movement controller

**Expected behavior**

Moving at the same speed diagonally as you'd do going up, left, down and right

**System:**
 - LITIENGINE version: 0.5.0-beta

**Comment by TheRamenChef** [comment]
Why should that be the expected behavior?

**Comment by itsmexi** [comment]
Well, maybe not expected behaviour per se. But rather a way to do so in an easily accessible way. A flag or a normalization function a la Unity if the user wishes that behaviour! :-)

**Comment by Gamebuster19901** [comment]
> Why should that be the expected behavior?

Because the developer expects the controller to move the entity a specific distance per tick, and moving diagonally makes it move faster than that.
