### ISSUE TITLE
UtiLITI "Edit Spritesheet(s)" panel incorrectly sized

### ISSUE THREAD

**Issue by Ferexx** [gurkenlabs/litiengine#364]
When importing a spritesheet in UtiLITI, after selecting the spritesheet to import, the "edit" panel that comes up is too narrow by a few pixels. It cuts off the right side of the content by a small amount.

1. Open UtiLITI
2. Click on 'Resources' > 'Import Spritesheets'
3. Select any spritesheet and click 'Open'.
4. The panel that comes up is incorrectly sized, see error.

**Expected behavior**
The panel to correctly display all information.

**Screenshots**
![image](https://user-images.githubusercontent.com/32805567/103289158-6b7f3c00-49de-11eb-89bf-5f5812580a85.png)

**Your System:**
 - OS: Windows
 - UtiLITI version: 0.5.0-beta
 - Screen resolution: 1920x1080

**Comment by pythonian23** [comment]
Also a problem with 2256x1504
