### ISSUE TITLE
utiLITI - locations not matching

### ISSUE THREAD

**Issue by pythonian23** [gurkenlabs/litiengine#370]
**Describe the bug**
1. The grid doesn't match up with the map's tiles

2. The mouse and the actions performed are in completely different location

**To Reproduce**
- Grid
  1. Open file in utiLITI
- Mouse
  1. Open file in utiLITI
  2. Add a Collisionbox

**Expected behavior**
1. The tiles of the map match up with the grid
2. Creating things happens where the mouse is

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/63051526/106360423-b08aeb00-635b-11eb-81ac-fbcafdf95e46.png)
2. ![image](https://user-images.githubusercontent.com/63051526/106360453-d1534080-635b-11eb-816f-9b1968e28a92.png)

**Your System:**
 - OS: Windows 10
 - LITIENGINE version: 0.5.0-beta
 - Screen resolution: 2256x1504

**Comment by nightm4re94** [comment]
This is identical to #275. Closing the issue in order to discuss the issue in only one place. Thanks for reporting!
