### ISSUE TITLE
Unable to launch utiliti executable on windows

### ISSUE THREAD

**Issue by Gamebuster19901** [gurkenlabs/litiengine#380]
**Describe the bug**
Utiliti executable is unable to launch on windows for some people.

**Error message*
The error message you get either in your console or the `crash.txt` located in your program's root directory.
```
This application requires Java Runtime Environment 1.8.0
```

**To Reproduce**
1. Launch `utiliti-v0.5.1-beta.exe`

**Screenshots**
![image](https://user-images.githubusercontent.com/7155747/110732844-ee005500-81f2-11eb-898c-b5c0d1794a52.png)

![image](https://user-images.githubusercontent.com/7155747/110732715-b2658b00-81f2-11eb-87af-e4155505d3f0.png)

**Affected systems:**
```
 - OS: Windows 7 (Virtual Machine)
 - LITIENGINE version: 0.5.1-beta
 - Java JDK/JRE version: `OpenJDK 1.8.0_265`, `OpenJDK 1.8.0_282`
 - Screen resolution: `1024x768 (Virtual Machine)`
 ```
 ```
 - OS: Windows 10.0.19041.804
 - LITIENGINE version: 0.5.1-beta
 - Java JDK/JRE version: `OpenJDK 1.8.0_282`
 - Screen resolution: Unknown
```
**Additional context**
From Discord: https://discord.com/channels/326074836508213258/804040170504192031/819215519999721472

**Comment by steffen-wilke** [comment]
Fixed with `v0.5.2-beta`. We're now bundling the runtime with the editor.
