### ISSUE TITLE
Importing TileMap and Sprites Issues

### ISSUE THREAD

**Issue by eHag-FRU** [gurkenlabs/litiengine#401]
**Describe the bug**
Can not import tilemap files that are valid files. A black screen appears with nothing. When I go to try and import it again, it asks for confirmation to replace the map.

**Stack Trace**
The error message you get either in your console or the `crash.txt` located in your program's root directory.
N/A

**To Reproduce**
1. Go to Map
2. Click on Import
3. Click .tmx file
4. Nothing Loads

**Expected behavior**
The map is to load in and show up in the preview.

**Screenshots**
![image]((https://user-images.githubusercontent.com/83028849/118190403-0ff39f00-b411-11eb-9db7-e5266f6733e5.png))
![image](https://user-images.githubusercontent.com/83028849/118190419-184bda00-b411-11eb-876c-b30a120036c8.png)
![image](https://user-images.githubusercontent.com/83028849/118190450-20a41500-b411-11eb-80e4-7b765cbef816.png)
![image](https://user-images.githubusercontent.com/83028849/118190469-27328c80-b411-11eb-9ec8-8bc37b3efe47.png)

**Your System:**
 - OS: Windows 10
 - LITIENGINE version: 0.5.1-beta
 - Java JDK/JRE version: jdk 14
 - Screen resolution: [e.g. 1920x1080]

**Additional context**
utiLITI v0.5.1-beta

**Comment by eHag-FRU** [comment]
I did find out through the log file for utiLITI that the version of Tiled needed to be 1.2.X or lower. The latest version is 1.6.X

**Comment by nightm4re94** [comment]
Please attach the log file or a stack trace for us to reproduce this.

**Comment by Gamebuster19901** [comment]
Seems like this might be #374

**Comment by nightm4re94** [comment]
You're right, I think we can consider this solved.
