### ISSUE TITLE
Missing player after loading new environment

### ISSUE THREAD

**Issue by ichbintobias2** [gurkenlabs/litiengine#407]
**Describe the bug**
When I switch into a new environment by going to its respective entrance the new environment loads and places you at the correct spawn but the player sprite is missing afterwards. A notification to press the button 'e' that appears when you stand next to an entrance indicates that the player is actually at the correct spot, just invisible. Also, it cannot be moved with WASD either.
If you revert the latest commit on the branch it starts working again, indicating that it has something to do with the trigger properties that I started using but if you start the game with debugger you can see that the properties get read correctly.

**Stack Trace**
No log output in the console or crash.txt other than the info that Tiled 1.6.0 was used instead of 1.2.x.

**To Reproduce**
1. Clone the project and check out the branch 'Map'
1. Start the game and press enter to get ingame
2. the ingame screen willl load and you will already stand at the correct spot to reproduce the error
3. Press the button 'e' as indicated
4. the bug occurs as described above

**Expected behavior**
The player should appear and the controls should work normally.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/58326385/122677797-2e08a800-d1e4-11eb-83cd-b237591da1d7.png)

**Your System:**
 - OS: Windows 10
 - LITIENGINE version: 0.5.0 but 0.5.1 was also tested
 - Java JDK/JRE version: AdoptOpenJDK 11.0.11
 - Screen resolution: 3840x2160

**Additional context**
Full sample project: https://github.com/ichbintobias2/pokegame.git (remember, branch map)
The critical methods for this are 'interact' in InteractButton.java and 'changeLocation' in LocationTriggers.java
I'm on your Discord under the name 'MLGeeZuZ' if quicker communication is required

**Comment by Gamebuster19901** [comment]
When you say reverting a commit fixes the issue, are you referring to commit https://github.com/ichbintobias2/pokegame/commit/3d81c740a78f4f96f59aed1a7873fe6b8ed728fd ?

**Comment by ichbintobias2** [comment]
The current commit is [3d81c74](https://github.com/ichbintobias2/pokegame/commit/3d81c740a78f4f96f59aed1a7873fe6b8ed728fd) but I meant the last one without the described bug is [675b346](https://github.com/ichbintobias2/pokegame/commit/675b346c497c683d29e258b2b1980c9516705a2e).

**Comment by nightm4re94** [comment]
Your Trigger logic sets the Player position to the spawnpoint's position on the new Map, but never actually adds the Player to the environment. Use `Game.world().environment().getSpawnpoint(targetSpawn).spawn(Player.instance());` to replace `de.tobias.pokegame.frontend.screens.LocationTriggers:line 15`. The spawn point magic will do the rest.
