### ISSUE TITLE
it cant run using adoptopenjdk 8.0.292.10 hotspot

### ISSUE THREAD

**Issue by zaze06** [gurkenlabs/litiengine#408]
**Describe the bug**
i cant start the engin becus i don't have jre 8

**Stack Trace**
The error message you get either in your console or the `crash.txt` located in your program's root directory.
no crach

**To Reproduce**
1. download and instal adoptopenjdk 8
2. run the exe

**Expected behavior**
the engine starts

**Screenshots**
![image](https://user-images.githubusercontent.com/54169874/123769997-2921b380-d8ca-11eb-921a-104a34661830.png)

**Your System:**
 - OS: Windows 10 21H1
 - LITIENGINE version: 0.5.1-beta
 - Java JDK/JRE version: adoptopenjdk jdk-8.0.292.10-hotspot
 - Screen resolution: 1680x1050

**Additional context**
nop sorry

**Comment by nightm4re94** [comment]
Closing this for being a duplicate. See #380.
