### ISSUE TITLE
Cosmetic improvments to the AssetPanelItem

### ISSUE THREAD

**Issue by jdeblander** [gurkenlabs/litiengine#419]
**What feature / which classes are you referring to?**
The [AssetPanelItem ](https://github.com/gurkenlabs/litiengine/blob/master/utiliti/src/de/gurkenlabs/utiliti/swing/AssetPanelItem.java)in the utiliti editor. On the current master branch (not the released 0.5.1-beta)

**Describe what could be enhanced.**
In the utiliti editor, when using the assets panel, the imported assets have some minor displaying issue when the name of an asset is too large.
Currently there is a wraparound with a maximum of two rows. And when selected, it shows some basic action buttons on the item.

![image](https://user-images.githubusercontent.com/3458701/131127589-7c08c350-3b30-4ef7-97a6-2bfe974b0ff7.png)

Once, the wraparound occurs, the buttons seems to be squeezed on the bottom of the panel (red).

![image](https://user-images.githubusercontent.com/3458701/131127743-3f98aef0-1700-4b6a-955d-1320c24bc3b8.png)

In addition, it could be considered to center the text inside the AssetPanelItem (blue).

**Additional thoughts**
I've already had a look at it before reporting the issue.
But I was going back and forth between the used JTextArea, which is good for the wraparound and the current styling, and the JTextPane, where it is easier to center the text. beside that there should be enough space already for two rows and none squeezed buttons. I suppose there is some default spacing going on between the row of buttons and the text pane above.

Last but not least, this is a very minor issue. Just reporting this as a possible enhancement to the existing tool.
Please close this, if the existing behaviour is as intended.

**Comment by jdeblander** [comment]
I gave this another try today and came up with a solution here #420

**Comment by jdeblander** [comment]
I will close this issue as they main improvement, the button resize, is fixed in the PR.

**Comment by nightm4re94** [comment]
Thanks!
Note that you can also auto-close issues with keywords in your commits (see [here](https://github.blog/2013-01-22-closing-issues-via-commit-messages/)).
