### ISSUE TITLE
Update ImageLayer specification

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#467]
[\<imagelayer\>](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#imagelayer)

- [x] class: The class of the image layer (since 1.9, defaults to “”).
- [x] repeatx: Whether the image drawn by this layer is repeated along the X axis. (since Tiled 1.8)
- [x] repeaty: Whether the image drawn by this layer is repeated along the Y axis. (since Tiled 1.8)

**Comment by steffen-wilke** [comment]
Closing in favor or #462
