### ISSUE TITLE
GuiComponent.setX() and .setY() adjust child component positions twice

### ISSUE THREAD

**Issue by Hades948** [gurkenlabs/litiengine#475]
**Describe the bug**
GuiComponent.setX() and .setY() make a call to setLocation(). setLocation() adjusts the location of the children components based on the delta. But then setX() and setY() also adjust the respective values for the children components.

**To Reproduce**
1. Create a GuiComponent with a child GuiComponent.
2. Call setX or setY on the parent component
3. The child component is in the wrong position.

**Expected behavior**
Only adjust the children components in one spot. Probably just remove the code in setX and setY that does it and let setLocation handle it.

**Your System:**
- OS: Windows 11
- LITIENGINE version: 0.5.2
- Java JDK/JRE version: jdk-18.0.2.1
- Screen resolution: 3,840 x 2,160

**Additional context**
A work-around could be only using setLocation. But the tweening framework uses only setX and setY, even with TweenType.POSITION_XY. On that same note, it might make more sense to use setLocation for TweenType.POSITION_XY. Regardless, you should be able to get past this, too, if you overwrite setTweenValues in the GuiComponent to use setLocation instead.

**Comment by nightm4re94** [comment]
This has been resolved by https://github.com/gurkenlabs/litiengine/commit/506cfee6fabd75fef25d77b28deaee163feaea6b.
![guicomponent_location](https://user-images.githubusercontent.com/26114385/202036209-85e013b8-e96d-4c24-82c2-8af8dc5b0b1b.gif)
