### ISSUE TITLE
Implement possiblity to fade music

### ISSUE THREAD

**Issue by gurkenlabs** [gurkenlabs/litiengine#51]
If another track is being played the request of slowly fading out the first and/or fading in the second track arises.

From @TheRamenChef #173 **Add functionality for multiple music tracks to play**
> While playing multiple music tracks at once isn't inherently useful, it would help to be able to have two "versions" of a track playing at once, and switch between them using the gain controls.

**Comment by steffen-wilke** [comment]
The implementation of #120 can be used to fade the `SoundPlaybacks`
