### ISSUE TITLE
Allow dynamic entity scaling

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#57]
Scaling sprites is useful for non-pixelart-games, for example. When hitting ALT and using transformation handles in utiLITI, it should be possible to dynamically resize entities along with their sprites.

**Comment by gurkenlabs** [comment]
This is possible now by enabling the `stretch sprite` option for a prop.
We need to also make this available for a `Creature`.

**Comment by gurkenlabs** [comment]
Also, the `AnimationController`  allows to set a custom `AffineTransform` object that can just be set to scale the sprite of an entity.
