### ISSUE TITLE
Playing LITIengine games on a virtual machine the Mouse doesn't work properly

### ISSUE THREAD

**Issue by gurkenlabs** [gurkenlabs/litiengine#7]
When playing "Naughty Gnomes" on a virtual machine provided by **VMware Workstation 12 Player**, the mouse could not be used properly.

Maybe the Screensize from the main display is used instead of the remote display and therefore the distance calculations for the mouse are wrong.

**Comment by steffen-wilke** [comment]
I'm closing this issue, since it hasn't been of interest for more than a year now, and it's essentially no real-world issue.
