### ISSUE TITLE
Adjust Creature sprite naming conventions

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#777]
Instead of creature-walk-right.png, use creature-move-right.png for automatic animationcontroller initialization.
Moving is a more generic name that applies also to creatures without legs.

Furthermore, determining the sprite states and directions by splitting spritesheet names at '-' characters is super prone to errors and doesn't allow you to deviate from the order at all. You can't, for example, call a sprite 'spaceship1-yellow-idle' because the 'yellow' part is then interpreted as sprite state. Use RegEx to determine sprite states and directions.

**Comment by SushmitaGoswami** [comment]
As per the present implementation, I didn't find any place where state and direction is calculated by splitting the sprite name at '-' characters. As per my understanding, sprite name is calculated from state or direction. Would you please let me know if the 2nd point still relevant as per the current implementation? Thanks so much!
