### ISSUE TITLE
Enhance sprite dimension determination in sprite import panel

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#779]
Instead of providing pixel dimensions for the frames, let the user simply provide column and row counts. This way, one doesn't necessarily have to know what size their image file has. Also it's less typing and slightly more intuitive. 
[Pixelorama ](https://github.com/Orama-Interactive/Pixelorama) does this, for example:
![pixelorama-spritesheet-import](https://user-images.githubusercontent.com/26114385/211199760-ff731ee6-3a68-4f9b-b667-f4fb32cf5c0e.gif)

**Comment by bkebir** [comment]
Hello,

We're 2 students on an IT Masters course and we'd like to contribute to your project on this issue. Is this possible ?

**Comment by nightm4re94** [comment]
Hi @bkebir and welcome! I think this makes for a great first issue :)
Please make sure you've read the [contribution guide](https://github.com/gurkenlabs/litiengine/blob/main/CONTRIBUTING.md) before getting started.
Do you need additional information to get started or are you confident enough to dig around on your own?

**Comment by bkebir** [comment]
Hi @nightm4re94, 
Yes, we'd like to know a little more about how to get started with the project, and if you have any tips or advice about the feature to be created.
Example : where the existing system is located and how to test the functionality

**Comment by nightm4re94** [comment]
So this is the current situation:
https://github.com/gurkenlabs/litiengine/assets/26114385/20724956-4f1b-489d-9e84-fd495e81bab2
In utiLITI's `SpritesheetImportPanel`, there are [two spinners](https://github.com/gurkenlabs/litiengine/blob/main/utiliti/src/main/java/de/gurkenlabs/utiliti/swing/dialogs/SpritesheetImportPanel.java#L60-L61) that configure the spritesheet width and height.
When the spinners are updated, the [grid preview](https://github.com/gurkenlabs/litiengine/blob/main/utiliti/src/main/java/de/gurkenlabs/utiliti/swing/dialogs/SpritesheetImportPanel.java#L636), the [keyframe table](https://github.com/gurkenlabs/litiengine/blob/main/utiliti/src/main/java/de/gurkenlabs/utiliti/swing/dialogs/SpritesheetImportPanel.java#L474), and the [animation preview](https://github.com/gurkenlabs/litiengine/blob/main/utiliti/src/main/java/de/gurkenlabs/utiliti/swing/dialogs/SpritesheetImportPanel.java#L499) are also updated.
Instead of specifying the spritesheet width and height in pixels, we want instead to pick the image width and height in frames.
I think a good example of the intended behaviour can be found in the "[Pixelorama ](https://github.com/Orama-Interactive/Pixelorama)" software:
![pixelorama-spritesheet-import](https://user-images.githubusercontent.com/26114385/211199760-ff731ee6-3a68-4f9b-b667-f4fb32cf5c0e.gif)

**Comment by bkebir** [comment]
@nightm4re94 Hello, can you go and see the issue we have encountered a problem, impossible to run 0.6.0 litiengine #793

**Comment by bkebir** [comment]
@nightm4re94 Hello, can you go and see the issue we have encountered a problem, impossible to run 0.6.0 litiengine, problem with JAVA 21, but it works again when you go back to an earlier version of the project https://github.com/gurkenlabs/litiengine/issues/794

**Comment by nightm4re94** [comment]
Thank you, I am getting notified for all issues created. No need to mention them here, please keep this thread exclusive to this issue.
