### ISSUE TITLE
More information on features

### ISSUE THREAD

**Issue by sroboubi** [gurkenlabs/litiengine#78]
I understand that providing documentation on features that are not fully developed or finalized is not your highest priority, but could you provide a description of the features that exist. For example you mention that you have an incorporated physics engine. Is it based on anything (box2d? dyn4j?) or written from scratch? Does it do CCD? Does it support concave polygons? Just basic information like that would help me (and probably others) decide if we can use this library or not.
Thanks in advance.

**Comment by gurkenlabs** [comment]
Hi sroboubi,
thank you for your interest in the engine. 

The physics engine **isn't based on any library** and written entirely from scratch. 
It is currently based on an **AABB implementation** that kinda supports CCD by a ray-cast approximation.

Hope this basic information answers your question.
