### ISSUE TITLE
Cannot open utiliti UI on Mac OS 

### ISSUE THREAD

**Issue by przemyslawmagiera** [gurkenlabs/litiengine#790]
**Describe the bug**
Cannot open utiliti UI on Mac OS Ventura 13.4

**Stack Trace**
n/a

**To Reproduce**
1. Download liteengine sdk 0.5.2-beta-macos
2. Unzip, open the litiengine-utiliti
3. Mac shows window "can't open app" or after "chmod +x litiengine-utiliti" "app is broken(damaged)"

**Expected behavior**
UI opens. 

**Screenshots**
n/a

**Your System:**
 - OS: Mac OS Ventura 13.4
 - LITIENGINE version: 0.5.2-beta
 - Java JDK/JRE version: Amazon correcto 17
 - Screen resolution: n/a

**Additional context**

**Comment by nightm4re94** [comment]
We can't currently reproduce this yet, but at least we are purchasing a preowned Mac soon to be able to test on MacOS.

**Comment by iamllcoolray** [comment]
Were you all able to identify the cause of the bug? 

System:

- OS: macOS Monterey 12.6.7
- LITIENGINE version: 0.5.2-beta
- Java JDK/JRE version: 20

Screenshot: 

<img width="254" alt="utiliti-can't-be-opened" src="https://github.com/gurkenlabs/litiengine/assets/20143111/07992a4e-3537-4da7-84db-247aa007162b">

**Comment by iamllcoolray** [comment]
So I found a solution that should fix the permissions of utiLITI on macOS.

**The command that I ran in the terminal:**

    chmod +x /Applications/litiengine-sdk-v0.5.2-beta-macos/utiliti/litiengine-utiliti.app/Contents/MacOS/*

**Results:**

<img width="1270" alt="Screen Shot 2023-10-08 at 10 55 07 AM" src="https://github.com/gurkenlabs/litiengine/assets/20143111/1a8ce559-8356-409d-9a15-b93c50482586">

**System:**

- OS: macOS Monterey 12.6.7
- LITIENGINE version: 0.5.2-beta
- Java JDK/JRE version: 20

**Comment by nightm4re94** [comment]
oh, that's awesome!
Where do you think Mac users can benefit from this information the most?

**Comment by iamllcoolray** [comment]
There could be a subsection that lets Mac users know how to give utiLITI executable permissions.

I see multiple places that may be great to inform Mac users (one or all of these places could be helpful):

- [Get LITIENGINE](https://litiengine.com/docs/getting-started/get-litiengine/) under the "Down the LITIENGINE SDK".
- [utiLITI Section](https://litiengine.com/docs/utiliti-editor/) under "How to Install/Setup utiLITI".
- [Creating a Platformer](https://litiengine.com/docs/tutorials/creating-a-platformer/) under "Creating a project in utiLITI".
- [Creating an Arkanoid Clone](https://litiengine.com/docs/tutorials/creating-an-arkanoid-clone/) under "How to create maps, use them with utiLITI and import them as a .litidata file".
- [Modifying Example Projects](https://litiengine.com/docs/tutorials/modifying-example-projects/) under "Chapter 4. UtiLITI run and utilize it".

**e.g.**

If you're on Mac after you download utiLITI you will have to execute this command below in Terminal to give executable permissions to utiLITI: (make sure to replace the Xs with the correct version number listed on the folder)

    chmod +x /Applications/litiengine-sdk-vX.X.X-beta-macos/utiliti/litiengine-utiliti.app/Contents/MacOS/*

**Comment by nightm4re94** [comment]
Thank you so much for the input!

**Comment by iamllcoolray** [comment]
No problem anytime.
