### ISSUE TITLE
Link to download 0.6.0 are incorrect on Itch.io

### ISSUE THREAD

**Issue by costalfy** [gurkenlabs/litiengine#797]
Hi, all links to download LitiEngine 0.6.0 redirect to Itchio and it's not the correct version we download. Actually it is the 0.5.2-beta
![2023-11-30 17_03_47-Download LITIENGINE SDK by gurkenlabs - itch io — Mozilla Firefox](https://github.com/gurkenlabs/litiengine/assets/1092544/7bd8d0fc-a4d5-4149-821b-9b140ceb96d9)
![2023-11-30 17_08_41-Download LITIENGINE SDK by gurkenlabs - itch io — Mozilla Firefox](https://github.com/gurkenlabs/litiengine/assets/1092544/d336291c-c559-494a-a9de-e7d0238b3e77)

**Comment by nightm4re94** [comment]
As mentioned in the release notes:
> The LITIENGINE library 0.6.0 is ready for consumption already, please stand by while we get the utiLITI packages for windows, mac, and linux ready.
I hope to find the time to publish new LITIENGINE SDK bundles in the next three weeks.
