### ISSUE TITLE
Exception occurred applying plugin request "de.gurkenlabs.semverguru"

### ISSUE THREAD

**Issue by jianh73** [gurkenlabs/litiengine#818]
**Describe the bug**
When I try to build 0.8.0, I got error message "An exception occurred applying plugin request [id: 'de.gurkenlabs.semverguru', version: '1.3'] 

**Stack Trace**
Build file '/Users/jian/Documents/projects/litiengineprojects/litiengine/build.gradle' line: 1

An exception occurred applying plugin request [id: 'de.gurkenlabs.semverguru', version: '1.3']
> Failed to apply plugin 'de.gurkenlabs.semverguru'.
   > repository not found: /Users/jian/Documents/projects/litiengineprojects/litiengine

**To Reproduce**
I am using IntelliJ CE 2030.3.6 on Mac
Gradle 8.5
java 21.0.2

Thanks for any suggestion!

**Your System:**
I am using IntelliJ CE 2030.3.6 on Mac
Gradle 8.5
java 21.0.2

**Comment by iamllcoolray** [comment]
This issue was resolved a while back and de.gurkenlabs.semverguru should be at version 1.4. The workaround I found was downloading the project from the parent repo and pushing that to your forked repo. This should resolve all of your issues.

**Comment by jianh73** [comment]
@iamllcoolray Thank you for your quick response. I am not sure I understand the term of "parent repo". I am using command "git clone https://github.com/gurkenlabs/litiengine.git" to clone the repo.

**Comment by nightm4re94** [comment]
Since your clone is using Gradle 8.5 and SemVerGuru 1.3, you have not checked out the most recent revision of LITIENGINE (which is at Gradle 8.7 and SemVerGuru 1.4).
