### ISSUE TITLE
Improve Speechbubble implementation

### ISSUE THREAD

**Issue by gurkenlabs** [gurkenlabs/litiengine#98]
It should provide the possibility to adjust the appearance.

- [ ] Indicator location (bottom-mid, left-mid, ...)
- [ ] Speechbubble alignment
- [ ] Speechbubble vertical alignment
- [ ] Speechbubble border radius
- [x] Render indicator
- [x] Color
- [x] BG-Paint
- [x] Border Color
- [ ] Padding
- [ ] Fixed on Screen
- [ ] Fixed in Environment
- [ ] Make use of Path2D.curveTo, provide an additional indicator style
- [x] it should be possible to set the Color values and especially the alpha.

**Comment by steffen-wilke** [comment]
https://forum.litiengine.com/d/97-what-do-you-have-of-dialoge-box-or-text-display-features
